### ISSUE TITLE
Creatre base model class

### ISSUE THREAD

**Issue by RignonNoel** [RignonNoel/plateforme_contribution#1]
## Application projects
 - Project
  - Name
  - Language/Technology (optionnal)
  - Description
 - Organization
  - Name
  - Logo (optionnal)
  - Url (optionnal)

##Application members
 - Member
 - Contribution
  - Url
  - Description
  - Project (optionnal)

**Comment by willkoua** [comment]
Des éléments que j'ai ajouté dans project:
- date_created (pour date de creation)
- date_modified(derniere modification)
- date_deleted(date d'archivage)
Est ce qu'il faudrait les ajouter aussi dans organisation?
